# Generated by Django 5.0.3 on 2024-03-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_userreg_address_remove_userreg_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreg',
            name='address',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userreg',
            name='phone_no',
            field=models.IntegerField(null=True),
        ),
    ]
